// Temp only, because I can't figure out how to access environment secrets.
export const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZnV0Z2pnZmxna2NreHJla3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwMTk1NDEsImV4cCI6MjA0ODU5NTU0MX0.pIQlsN43fHNmB1MCjONz6jomwz3x3vdgfGyfSlmWw_U'
