name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Inject Supabase Key
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Injecting Supabase key into config.js"
          sed -i "s/__SUPABASE_KEY__/${SUPABASE_KEY}/g" ./config.js

      - name: Commit updated config.js
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./config.js
          git commit -m "Update config.js with Supabase API Key"
          git push
