name: Build and Deploy to GitHub Pages
on: 
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Debug: Print all available environment variables
      - name: Print all environment variables
        run: env

      # Debug: Explicitly check the variable
      - name: Check Specific Variable
        env:
          VITE_SUPABASE_KEY: ${{ vars.VITE_SUPABASE_KEY }}
        run: |
          echo "Checking Supabase Key"
          echo "VITE_SUPABASE_KEY length: ${#VITE_SUPABASE_KEY}"
          if [ -z "$VITE_SUPABASE_KEY" ]; then
            echo "VITE_SUPABASE_KEY is not set"
            exit 1
          else
            echo "VITE_SUPABASE_KEY is set"
          fi

      # Build the project
      - name: Build the project
        env:
          VITE_SUPABASE_KEY: ${{ vars.VITE_SUPABASE_KEY }}
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
